title: スクールガールストライカーズ2 アドベントカレンダー 2019
show_downloads: false
theme: slate
permalink: /:year/:month/:day/:title:output_ext
url: https://kawa0x0a.github.io
baseurl: /SchoolGirlStrikersAdventCalendar2019
